### ISSUE TITLE
Fail to use the extension. 

### ISSUE THREAD

**Issue by myz9906** [ali-h-kudeir/ChatGPT-Google-Colab#1]
After installing the extension, it still cannot access the ChatGPT even though login the OpenAI account. Could please provide an API to this extension? I cannot find where I can type the API in this extension.
![image](https://user-images.githubusercontent.com/54363085/222368079-64fb30b3-73e2-4f68-8e7d-b5edf0773f67.png)

**Comment by ahk-d** [comment]
Hi @myz9906. It should automatically connect to ChatGPT's server and retrieve the answer without the need for any API.
Can you please provide your browser version and your OS? I am planning to update the extension this weekend, and I will also make a tutorial video on https://www.youtube.com/@codequation

**Comment by myz9906** [comment]
> Hi @myz9906. It should automatically connect to ChatGPT's server and retrieve the answer without the need for any API. Can you please provide your browser version and your OS? I am planning to update the extension this weekend, and I will also make a tutorial video on https://www.youtube.com/@codequation

@ali-h-kudeir My Chrome browser version is 110.0.5481.178. I have tested the extension in Win 10 and Win 11. However, both of the tests cannot connect the ChatGPT's server.
