### ISSUE TITLE
Rapidly creates new chatgpt conversations while typing a question

### ISSUE THREAD

**Issue by fractaldna22** [ali-h-kudeir/ChatGPT-Google-Colab#3]
after the first response, if you change the question it sends a new conversation for every new letter and rapidly exhausts your usage limit of chatgpt for an hour. Please make it stop sending new chats until user clicks send.

**Comment by ahk-d** [comment]
@fractaldna22 Thank you for the catch. I have fixed it and I am updating both Firefox and Chrome extensions.
